### PR TITLE
Freeze version for peewee.

### PR DESCRIPTION
**Pull request by art1415926535**
Latest version graphene-peewee-async is not working with latest peewee version.
Peewee>2.10.2 doesn't have class Clause.

```python
File "/usr/local/lib/python3.6/site-packages/graphene_peewee_async/queries.py", line 4, in <module>
    from peewee import (
ImportError: cannot import name 'Clause'
```

### CODE REVIEW

**Comment by slash-oleh** [comment]
Yes, there is no support for recently released 3rd peewee version yet, so it should be frozen for some time. Thanks for PR, I will make version from it in 24h and start working on `peewee>=3.0` support.
